// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/tools/list-trails.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/utils/mapData.js
var trailData = {
  trail1: {
    name: "Forest Loop Trail",
    color: "#FF6B6B",
    // Red
    points: [
      { lat: -3.0989414, lon: -59.9763193, imageId: "840083121440177" },
      { lat: -3.0990414, lon: -59.9764193, imageId: "840083121440178" },
      { lat: -3.0991414, lon: -59.9765193, imageId: "840083121440179" }
      // Add more points here - placeholder for ~200 points
    ]
  },
  trail2: {
    name: "River Trail",
    color: "#4ECDC4",
    // Teal
    points: [
      { lat: -3.0992414, lon: -59.9766193, imageId: "840083121440180" },
      { lat: -3.0993414, lon: -59.9767193, imageId: "840083121440181" },
      { lat: -3.0994414, lon: -59.9768193, imageId: "840083121440182" }
      // Add more points here - placeholder for ~200 points
    ]
  },
  trail3: {
    name: "Mountain Path",
    color: "#45B7D1",
    // Blue
    points: [
      { lat: -3.0995414, lon: -59.9769193, imageId: "840083121440183" },
      { lat: -3.0996414, lon: -59.9770193, imageId: "840083121440184" },
      { lat: -3.0997414, lon: -59.9771193, imageId: "840083121440185" }
      // Add more points here - placeholder for ~200 points
    ]
  },
  trail4: {
    name: "Canopy Walk",
    color: "#96CEB4",
    // Green
    points: [
      { lat: -3.0998414, lon: -59.9772193, imageId: "840083121440186" },
      { lat: -3.0999414, lon: -59.9773193, imageId: "840083121440187" },
      { lat: -3.1000414, lon: -59.9774193, imageId: "840083121440188" }
      // Add more points here - placeholder for ~200 points
    ]
  },
  trail5: {
    name: "Wildlife Trail",
    color: "#FFEAA7",
    // Yellow
    points: [
      { lat: -3.1001414, lon: -59.9775193, imageId: "840083121440189" },
      { lat: -3.1002414, lon: -59.9776193, imageId: "840083121440190" },
      { lat: -3.1003414, lon: -59.9777193, imageId: "840083121440191" }
      // Add more points here - placeholder for ~200 points
    ]
  },
  trail6: {
    name: "Scenic Overlook",
    color: "#DDA0DD",
    // Plum
    points: [
      { lat: -3.1004414, lon: -59.9778193, imageId: "840083121440192" },
      { lat: -3.1005414, lon: -59.9779193, imageId: "840083121440193" },
      { lat: -3.1006414, lon: -59.9780193, imageId: "840083121440194" }
      // Add more points here - placeholder for ~200 points
    ]
  },
  trail7: {
    name: "Ancient Grove",
    color: "#F0932B",
    // Orange
    points: [
      { lat: -3.1007414, lon: -59.9781193, imageId: "840083121440195" },
      { lat: -3.1008414, lon: -59.9782193, imageId: "840083121440196" },
      { lat: -3.1009414, lon: -59.9783193, imageId: "840083121440197" }
      // Add more points here - placeholder for ~200 points
    ]
  }
};
var getAllTrails = () => {
  return Object.entries(trailData).map(([key, trail]) => ({
    id: key,
    ...trail
  }));
};
var getTrailById = (trailId) => {
  return trailData[trailId];
};

// src/lib/mcp/tools/list-trails.ts
var list_trails_default = defineTool({
  name: "list_trails",
  title: "List campus trails",
  description: "List all mapped UFAM campus trails with their id, name, display color and number of mapped points.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const trails = getAllTrails().map((trail) => ({
      id: trail.id,
      name: trail.name,
      color: trail.color,
      pointCount: trail.points.length
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(trails, null, 2) }],
      structuredContent: { trails }
    };
  }
});

// src/lib/mcp/tools/get-trail.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z } from "npm:zod@^3.23.8";
var get_trail_default = defineTool2({
  name: "get_trail",
  title: "Get trail details",
  description: "Get one UFAM campus trail by id, including every mapped point (latitude, longitude and Mapillary street-view image id).",
  inputSchema: {
    trailId: z.string().min(1).describe("Trail id, e.g. `trail1`. Use `list_trails` to discover ids.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ trailId }) => {
    const trail = getTrailById(trailId);
    if (!trail) throw new ToolError(`No trail found with id "${trailId}".`);
    const result = { id: trailId, ...trail };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: { trail: result }
    };
  }
});

// src/lib/mcp/tools/find-nearest-point.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z2 } from "npm:zod@^3.23.8";
function distanceMeters(aLat, aLon, bLat, bLon) {
  const R = 6371e3;
  const toRad = (v) => v * Math.PI / 180;
  const dLat = toRad(bLat - aLat);
  const dLon = toRad(bLon - aLon);
  const h = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(aLat)) * Math.cos(toRad(bLat)) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
}
var find_nearest_point_default = defineTool3({
  name: "find_nearest_trail_point",
  title: "Find nearest trail point",
  description: "Find the closest mapped trail points to a latitude/longitude on the UFAM campus, with distance in meters.",
  inputSchema: {
    lat: z2.number().describe("Latitude in decimal degrees."),
    lon: z2.number().describe("Longitude in decimal degrees."),
    limit: z2.number().int().positive().default(5).describe("How many nearby points to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ lat, lon, limit }) => {
    const points = getAllTrails().flatMap(
      (trail) => trail.points.map((point) => ({
        trailId: trail.id,
        trailName: trail.name,
        lat: point.lat,
        lon: point.lon,
        imageId: point.imageId,
        distanceMeters: Math.round(distanceMeters(lat, lon, point.lat, point.lon))
      }))
    );
    const nearest = points.sort((a, b) => a.distanceMeters - b.distanceMeters).slice(0, limit ?? 5);
    return {
      content: [{ type: "text", text: JSON.stringify(nearest, null, 2) }],
      structuredContent: { points: nearest }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "campus-navigator-ufam",
  title: "campus-navigator-ufam",
  version: "0.1.0",
  instructions: "Public read-only tools for the UFAM campus navigator. Use `list_trails` to see mapped campus trails, `get_trail` for a trail's full point list, and `find_nearest_trail_point` to locate the closest mapped points to a coordinate.",
  tools: [list_trails_default, get_trail_default, find_nearest_point_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.3/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
